stages:
  - setup_build_test

setup_build_test:
  stage: setup_build_test
  script:
    - echo "Enter setup stage..."
    - ./scripts/install_requirements.sh
    - ./scripts/clean.sh
    - ./scripts/ensure_conda_env.sh
    - ./scripts/build.sh
    - ./scripts/install.sh
    - ./scripts/run_tests.sh
  artifacts:
    when: always
    paths:
      - tests/test_artifacts/*.txt
    expire_in: 4 week
  tags:
    - ar
    #- alba
